services:
  ai-service:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ai-service
    env_file:
      - ../../.env
    ports:
      - "8000:8000"
    volumes:
      - ../../src:/app/src
      - ../../models:/app/models
    networks:
      - shared-ml-network

networks:
  shared-ml-network:
    external: true